# app.R
# MEPS High-Cost Users — Shiny Portfolio App
# Run: shiny::runApp() from the project root
# Deploy: rsconnect::deployApp() from the project root

# ── Packages ──────────────────────────────────────────────────────────────────
pkgs <- c("shiny", "shinydashboard", "ggplot2", "dplyr", "DT",
          "scales", "tidyr", "readr")
for (p in pkgs) if (!require(p, character.only = TRUE, quietly = TRUE))
  install.packages(p)

library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr)
library(DT)
library(scales)
library(tidyr)
library(readr)

# ── Helper: safe CSV loader ───────────────────────────────────────────────────
load_csv <- function(path) {
  if (file.exists(path)) read_csv(path, show_col_types = FALSE) else NULL
}

# ── Load pre-computed outputs (generated by the pipeline) ────────────────────
df_analytical  <- if (file.exists("data/processed/meps_analytical.rds"))
                    readRDS("data/processed/meps_analytical.rds") else NULL

df_twopart     <- load_csv("output/tables/table_twopart_profiles.csv")
df_ame_b1      <- load_csv("output/tables/ame_B1_top5.csv")
df_ame_b2      <- load_csv("output/tables/ame_B2_top1.csv")
df_ame_glm     <- load_csv("output/tables/ame_glm_GB_main.csv")
df_r2          <- load_csv("output/tables/deviance_r2_glm.csv")
df_thresholds  <- load_csv("output/tables/thresholds.csv")
df_zero        <- load_csv("output/tables/zero_expenditure_stats.csv")

fig_paths <- list(
  hist        = "output/figures/fig1_expenditure_distribution.png",
  forest_log  = "output/figures/fig2_ame_logistic_forest.png",
  forest_glm  = "output/figures/fig3_ame_glm_forest.png",
  interaction = "output/figures/fig4_interaction_morbidity_insurance.png",
  r2          = "output/figures/fig5_devr2_incremental.png"
)

# ── UI ────────────────────────────────────────────────────────────────────────
ui <- dashboardPage(
  skin = "blue",

  dashboardHeader(title = "MEPS 2022 — High-Cost Users"),

  dashboardSidebar(
    sidebarMenu(
      menuItem("Overview",          tabName = "overview",     icon = icon("info-circle")),
      menuItem("Sample",            tabName = "sample",       icon = icon("table")),
      menuItem("Expenditure",       tabName = "expenditure",  icon = icon("chart-bar")),
      menuItem("Logistic Models",   tabName = "logistic",     icon = icon("project-diagram")),
      menuItem("GLM Models",        tabName = "glm",          icon = icon("dollar-sign")),
      menuItem("Two-Part Profiles", tabName = "twopart",      icon = icon("users")),
      menuItem("Interaction",       tabName = "interaction",  icon = icon("exchange-alt")),
      menuItem("Model Fit",         tabName = "fit",          icon = icon("chart-line"))
    )
  ),

  dashboardBody(
    tabItems(

      # ── Overview ─────────────────────────────────────────────────────────────
      tabItem(tabName = "overview",
        fluidRow(
          box(width = 12, title = "Who pays for whom: the economics of concentrated healthcare spending",
              status = "primary", solidHeader = TRUE,
              p("U.S. healthcare spending is extremely concentrated: a small share of individuals accounts for a disproportionate share of annual expenditure. This project uses the 2022 MEPS Full-Year Consolidated File (HC-243) to ask two questions:"),
              tags$ol(
                tags$li("Who ends up in the high-cost tail (top 5% and top 1% of annual expenditure)?"),
                tags$li("How much does the system actually spend on them, conditional on their characteristics?")
              ),
              p("The analysis applies a two-part microeconometric framework: a survey-weighted quasibinomial logistic model for tail membership, and a Gamma GLM with log link for conditional expenditure. Average marginal effects (AMEs) are computed via the delta method with survey weights explicitly passed through."),
              hr(),
              fluidRow(
                valueBoxOutput("box_n",         width = 3),
                valueBoxOutput("box_top5",      width = 3),
                valueBoxOutput("box_top1",      width = 3),
                valueBoxOutput("box_zero",      width = 3)
              )
          )
        )
      ),

      # ── Sample ───────────────────────────────────────────────────────────────
      tabItem(tabName = "sample",
        fluidRow(
          box(width = 12, title = "Analytical Sample — Key Variables",
              status = "info", solidHeader = TRUE,
              p("Adults 18+ from MEPS 2022 (HC-243). All estimates are survey-weighted."),
              DTOutput("table_sample")
          )
        )
      ),

      # ── Expenditure ──────────────────────────────────────────────────────────
      tabItem(tabName = "expenditure",
        fluidRow(
          box(width = 12, title = "Figure 1 — Distribution of Total Annual Healthcare Expenditure",
              status = "warning", solidHeader = TRUE,
              p("Log scale. Vertical lines mark the top 5% and top 1% thresholds (survey-weighted quantiles)."),
              uiOutput("fig_hist")
          )
        ),
        fluidRow(
          box(width = 6, title = "Expenditure Thresholds", status = "warning",
              DTOutput("table_thresholds")),
          box(width = 6, title = "Zero Expenditure", status = "warning",
              DTOutput("table_zero"))
        )
      ),

      # ── Logistic ─────────────────────────────────────────────────────────────
      tabItem(tabName = "logistic",
        fluidRow(
          box(width = 12, title = "Figure 2 — Average Marginal Effects: Logistic Models (Set B)",
              status = "success", solidHeader = TRUE,
              p("AMEs on the probability scale (percentage points). Points filled = p < 0.05. Reference: Private insurance, 0 chronic conditions, 18-34, Female, White Non-Hispanic, High Income, No SPD, No cancer."),
              uiOutput("fig_forest_log")
          )
        ),
        fluidRow(
          box(width = 12, title = "AME Table — Top 5% Model (B1)",
              status = "success",
              DTOutput("table_ame_b1")),
          box(width = 12, title = "AME Table — Top 1% Model (B2)",
              status = "success",
              DTOutput("table_ame_b2"))
        )
      ),

      # ── GLM ──────────────────────────────────────────────────────────────────
      tabItem(tabName = "glm",
        fluidRow(
          box(width = 12, title = "Figure 3 — Average Marginal Effects: Gamma GLM (Model G-B)",
              status = "danger", solidHeader = TRUE,
              p("AMEs in dollars on conditional expenditure E[Y | Y > 0]. Restricted to observations with positive total expenditure."),
              uiOutput("fig_forest_glm")
          )
        ),
        fluidRow(
          box(width = 12, title = "AME Table — GLM Main Effects (G-B)",
              status = "danger",
              DTOutput("table_ame_glm"))
        )
      ),

      # ── Two-Part Profiles ────────────────────────────────────────────────────
      tabItem(tabName = "twopart",
        fluidRow(
          box(width = 12, title = "Two-Part Expected Spending by Profile",
              status = "primary", solidHeader = TRUE,
              p("Reference profile: Female, 55-64, White Non-Hispanic, College+, Middle Income, No SPD, No cancer history. Morbidity and insurance vary across profiles."),
              p(strong("E[Y] = Pr(Y>0) × E[Y|Y>0).")),
              DTOutput("table_twopart"),
              hr(),
              plotOutput("plot_twopart", height = "420px")
          )
        )
      ),

      # ── Interaction ──────────────────────────────────────────────────────────
      tabItem(tabName = "interaction",
        fluidRow(
          box(width = 12, title = "Figure 4 — Morbidity × Insurance Interaction",
              status = "warning", solidHeader = TRUE,
              p("Predicted probability of top 5% status by number of chronic conditions, stratified by insurance type. Shaded bands = 95% CI."),
              uiOutput("fig_interaction")
          )
        )
      ),

      # ── Model Fit ────────────────────────────────────────────────────────────
      tabItem(tabName = "fit",
        fluidRow(
          box(width = 12, title = "Figure 5 — Deviance-Based Pseudo-R² Across Specifications",
              status = "info", solidHeader = TRUE,
              p("Comparison of deviance-based pseudo-R² for logistic and GLM models across three specifications (A: demographics; B: + morbidity; C: + morbidity × insurance interaction)."),
              uiOutput("fig_r2")
          )
        ),
        fluidRow(
          box(width = 12, title = "Model Fit Table", status = "info",
              DTOutput("table_r2"))
        )
      )

    ) # end tabItems
  ) # end dashboardBody
)

# ── Server ────────────────────────────────────────────────────────────────────
server <- function(input, output, session) {

  # Value boxes
  output$box_n <- renderValueBox({
    n <- if (!is.null(df_analytical)) nrow(df_analytical) else "—"
    valueBox(format(n, big.mark = ","), "Adults 18+ (n)", icon = icon("users"), color = "blue")
  })
  output$box_top5 <- renderValueBox({
    val <- if (!is.null(df_analytical) && "top5" %in% names(df_analytical))
      sprintf("%.1f%%", mean(df_analytical$top5, na.rm = TRUE) * 100) else "—"
    valueBox(val, "Top 5% threshold", icon = icon("arrow-up"), color = "yellow")
  })
  output$box_top1 <- renderValueBox({
    val <- if (!is.null(df_analytical) && "top1" %in% names(df_analytical))
      sprintf("%.1f%%", mean(df_analytical$top1, na.rm = TRUE) * 100) else "—"
    valueBox(val, "Top 1% threshold", icon = icon("exclamation"), color = "red")
  })
  output$box_zero <- renderValueBox({
    val <- if (!is.null(df_zero) && "p_zero" %in% names(df_zero))
      sprintf("%.1f%%", df_zero$p_zero[1] * 100) else "—"
    valueBox(val, "Zero expenditure", icon = icon("times-circle"), color = "green")
  })

  # Sample table
  output$table_sample <- renderDT({
    if (is.null(df_analytical)) return(datatable(data.frame(Message = "Run pipeline first")))
    vars <- intersect(c("insurance_status", "n_chronic_conditions_cat", "age_cat",
                        "sex", "race_ethnicity", "income_pct_fpl", "cancer_ever",
                        "mental_health_cat", "top5", "top1", "total_exp"),
                      names(df_analytical))
    df_analytical[, vars] |>
      head(500) |>
      datatable(options = list(pageLength = 15, scrollX = TRUE),
                caption = "First 500 rows of analytical dataset")
  })

  # Thresholds
  output$table_thresholds <- renderDT({
    if (is.null(df_thresholds)) return(datatable(data.frame(Message = "Run 02_clean.R")))
    datatable(df_thresholds, options = list(dom = "t"))
  })

  # Zero expenditure
  output$table_zero <- renderDT({
    if (is.null(df_zero)) return(datatable(data.frame(Message = "Run 02_clean.R")))
    datatable(df_zero, options = list(dom = "t"))
  })

  # Figures — render as image if file exists, else placeholder text
  render_fig <- function(path) {
    renderUI({
      if (file.exists(path))
        tags$img(src = path, style = "width:100%; max-width:900px;")
      else
        p(em("Figure not found. Run the pipeline to generate outputs."),
          style = "color:gray; padding:20px;")
    })
  }

  output$fig_hist        <- render_fig(fig_paths$hist)
  output$fig_forest_log  <- render_fig(fig_paths$forest_log)
  output$fig_forest_glm  <- render_fig(fig_paths$forest_glm)
  output$fig_interaction <- render_fig(fig_paths$interaction)
  output$fig_r2          <- render_fig(fig_paths$r2)

  # AME tables
  fmt_ame <- function(df) {
    if (is.null(df)) return(datatable(data.frame(Message = "Run pipeline first")))
    datatable(df |> mutate(across(where(is.numeric), ~ round(.x, 4))),
              options = list(pageLength = 15, scrollX = TRUE))
  }
  output$table_ame_b1  <- renderDT(fmt_ame(df_ame_b1))
  output$table_ame_b2  <- renderDT(fmt_ame(df_ame_b2))
  output$table_ame_glm <- renderDT(fmt_ame(df_ame_glm))

  # Two-part table
  output$table_twopart <- renderDT({
    if (is.null(df_twopart)) return(datatable(data.frame(Message = "Run 06_twopart_profiles.R")))
    df_fmt <- df_twopart |>
      mutate(
        pr_pos  = sprintf("%.1f%%", pr_pos  * 100),
        pr_top5 = sprintf("%.1f%%", pr_top5 * 100),
        pr_top1 = sprintf("%.1f%%", pr_top1 * 100),
        e_y_pos = dollar(e_y_pos),
        e_y     = dollar(e_y)
      )
    datatable(df_fmt, options = list(dom = "t", pageLength = 20))
  })

  # Two-part bar chart
  output$plot_twopart <- renderPlot({
    if (is.null(df_twopart)) return(NULL)
    df_twopart |>
      mutate(profile = paste(insurance_status, n_chronic_conditions_cat, sep = "\n")) |>
      ggplot(aes(x = reorder(profile, e_y), y = e_y, fill = insurance_status)) +
      geom_col(width = 0.7) +
      coord_flip() +
      scale_y_continuous(labels = dollar_format()) +
      scale_fill_brewer(palette = "Set2") +
      labs(
        title    = "Unconditional Expected Annual Spending by Profile",
        subtitle = "E[Y] = Pr(Y>0) × E[Y|Y>0]",
        x        = "Profile (Insurance × Morbidity)",
        y        = "Expected Annual Spending (USD)",
        fill     = "Insurance"
      ) +
      theme_bw(base_size = 13) +
      theme(legend.position = "bottom")
  })

  # Model fit table
  output$table_r2 <- renderDT({
    if (is.null(df_r2)) return(datatable(data.frame(Message = "Run 05_models_glm.R")))
    datatable(df_r2 |> mutate(across(where(is.numeric), ~ round(.x, 4))),
              options = list(dom = "t"))
  })

}

# ── Run ───────────────────────────────────────────────────────────────────────
shinyApp(ui, server)
