# 08_report.R
# MEPS High-Cost Patient Prediction Project
# Step 8: Render Analytical Summary
#
# Generates a professional Markdown summary of the project methodology and findings,
# and renders it to HTML. Reads the two-part profile table from CSV if available.

if (!require("rmarkdown")) install.packages("rmarkdown")
library(rmarkdown)

dir.create("docs", recursive = TRUE, showWarnings = FALSE)

cat("Generating analytical summary report...\n")

# Load two-part table if it exists (generated by 06_twopart_profiles.R)
twopart_table_md <- ""
twopart_csv <- "output/tables/table_twopart_profiles.csv"
if (file.exists(twopart_csv)) {
  tp <- read.csv(twopart_csv)
  # Format for Markdown
  tp_fmt <- tp
  tp_fmt$pr_pos   <- sprintf("%.1f%%", tp$pr_pos * 100)
  tp_fmt$pr_top5  <- sprintf("%.1f%%", tp$pr_top5 * 100)
  tp_fmt$pr_top1  <- sprintf("%.1f%%", tp$pr_top1 * 100)
  tp_fmt$e_y_pos  <- sprintf("$%s",    formatC(tp$e_y_pos,  format = "d", big.mark = ","))
  tp_fmt$e_y      <- sprintf("$%s",    formatC(tp$e_y,      format = "d", big.mark = ","))

  rows <- apply(tp_fmt, 1, function(r) {
    sprintf("| %s | %s | %s | %s | %s | %s | %s |",
            r["insurance_status"], r["n_chronic_conditions_cat"],
            r["pr_pos"], r["pr_top5"], r["pr_top1"],
            r["e_y_pos"], r["e_y"])
  })

  twopart_table_md <- paste0(
    "\n\n### Two-Part Expected Spending by Profile\n\n",
    "*Reference profile: Female, 55-64, White Non-Hispanic, College+, Middle Income, No SPD, No cancer history.*\n\n",
    "| Insurance | Morbidity | Pr(Y>0) | Pr(Top 5%) | Pr(Top 1%) | E[Y\\|Y>0] | E[Y] |\n",
    "|---|---|---|---|---|---|---|\n",
    paste(rows, collapse = "\n"),
    "\n\n*Note: E[Y] = Pr(Y>0) × E[Y|Y>0]. Uncertainty for E[Y] is not propagated (two-part product).*\n"
  )
}

rmd_content <- paste0("---
title: 'Who pays for whom: the economics of concentrated healthcare spending'
subtitle: 'A two-part microeconometric analysis of the 2022 Medical Expenditure Panel Survey'
author: 'Health Services Analyst Portfolio Project'
date: '`r Sys.Date()`'
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
---

## The problem, in one paragraph

U.S. healthcare spending is extremely concentrated: a small share of individuals accounts for a disproportionate share of annual expenditure, and this concentration is not a statistical accident — it is the central feature of how health insurance, clinical complexity, and access interact. Understanding *which* individuals land in that tail, and *why*, is a precondition for almost every applied question in health economics: actuarial pricing, risk adjustment under the ACA, Medicaid rate-setting, value-based contracting, and the design of reinsurance mechanisms. This project takes the 2022 MEPS Full-Year Consolidated File and asks two questions with different policy stakes: (1) who ends up in the high-cost tail, and (2) how much does the healthcare system actually spend on them, conditional on their characteristics. The answers turn out to tell a coherent story about clinical need, insurance coverage, and how access frictions show up in observed spending.

## Why the methodological choices matter — not just \"what I ran\"

The technical decisions in this project are not generic. Each one maps directly to a feature of the economic object being estimated.

### The distribution forces a two-part model

U.S. healthcare expenditure has two properties that break standard regression. First, a nontrivial fraction of the population (14.5% in this sample) spends zero in a given year — a mass point at the boundary. Second, conditional on spending something, the distribution is heavy-tailed and strictly positive. Running OLS on total spending would give coefficients that are neither good predictions nor interpretable marginal effects: the zero mass biases the slope, and the right skew inflates the residual variance.

The two-part model handles this cleanly by decomposing:

$$E[Y \\mid X] = \\Pr(Y > 0 \\mid X) \\times E[Y \\mid Y > 0, X]$$

The first stage (a logistic regression on participation) captures *whether* an individual enters the healthcare system at all. The second stage (a Gamma GLM with log link) captures *how much* they spend once they do. These are economically distinct margins: participation is about access and contact with the system; conditional spending is about clinical intensity once contact is made. A single-equation model conflates these margins and masks the policy-relevant mechanism.

### Why Gamma with log link, and not log-OLS

A common shortcut is to take logs of positive spending and run OLS. This has a known retransformation bias: $\\exp(E[\\log Y]) \\neq E[Y]$, and the gap depends on the residual variance. For heteroskedastic spending data, the bias is not small and it is not constant. The Gamma GLM with log link sidesteps the retransformation problem entirely by modeling $E[Y]$ directly on the original scale while allowing the mean-variance relationship to scale with the mean — which is the empirical pattern in expenditure data. This is standard practice in health economics since Manning and Mullahy (2001), and the choice signals to a reader that the analyst understands the actual generating process, not just the mechanics of fitting a line.

### Why survey weights and a complex design object are non-negotiable

MEPS is not a simple random sample. It uses stratified multi-stage cluster sampling with oversampling of policy-relevant subpopulations (low-income households, Hispanic and Black households). Unweighted estimates are biased for national quantities, and standard errors computed without the cluster/stratum structure are too small — often dramatically. Every model in this project is fit on a `svydesign` object, and average marginal effects are recomputed with the design weights explicitly passed through. This is the difference between producing numbers that describe the U.S. adult population and numbers that describe the convenience sample that happened to be surveyed.

### Why average marginal effects, not odds ratios

Logistic regression coefficients are log-odds, which have no direct policy interpretation. Someone reading \"the odds ratio for 4+ chronic conditions is 8.3\" cannot tell you how many additional people land in the top 5%. Average marginal effects translate the model back to the probability scale: having 4+ conditions raises the probability of being in the top 5% by 18.1 percentage points, averaged over the empirical covariate distribution. That is a number a health plan can use, a policymaker can cite, and a regulator can test.

### Why the interaction model exists but doesn't dominate

Specification C adds a morbidity × insurance interaction. It was included to test a specific hypothesis: does the return to clinical complexity (in probability or dollars) depend on coverage type? The data say yes, but modestly — the pseudo-R² gain over the main-effects model is trivial (0.113 vs. 0.111 in the logistic; 0.123 vs. 0.123 in the GLM). The economic reading is that the morbidity gradient is a clinical fact that travels across coverage environments; insurance primarily shifts the level of spending rather than the slope of the morbidity gradient. That is itself an economically interesting result, and it disciplines how the findings should be communicated.

## What the results actually say

Three findings organize the evidence.

**First, multimorbidity dominates.** The number of chronic conditions is the single strongest predictor of both high-cost tail membership and conditional spending. Moving from zero to four or more conditions raises the probability of landing in the top 5% by 18 percentage points, and raises conditional annual spending by about $19,400. A cancer history adds another $6,300; serious psychological distress adds $3,400. Once these clinical covariates are in the model, education and income-to-poverty ratio are essentially null. The socioeconomic gradient in spending appears to be largely attenuated once morbidity and insurance are accounted for, suggesting that much of the observed gradient operates through differences in clinical burden and coverage rather than around them. Policies that target spending concentration cannot bypass the clinical layer.

**Second, the insured-uninsured boundary is where the discontinuity lives.** Among the insured, the morbidity gradient is broadly similar across Private, Medicare/Other Public, and Medicaid coverage — the marginal effect of 4+ conditions on conditional spending ranges from roughly $17,500 to $21,000, differences that are detectable but not large relative to the baseline. The uninsured stratum is qualitatively different: the same clinical profile is associated with only about $12,000 in marginal conditional spending, and about half the probability of reaching the top 5%. This is the empirical footprint of an access friction, not of a health difference.

**Third, the two-part model makes the system-level implication legible.** For a 55–64-year-old woman with a modal demographic profile, expected total annual spending rises from $5,613 to $25,126 when morbidity moves from zero to 4+ conditions under Private insurance, and from $6,541 to $29,690 under Medicaid. For an otherwise identical uninsured individual, the same morbidity shift produces only $2,461 to $13,045. The gap between \"insured and sick\" and \"uninsured and sick\" is not explained by a participation margin — almost everyone with 4+ conditions spends something (Pr(Y>0) = 0.98 even uninsured). It is explained by the conditional margin: once care is accessed, the uninsured spend roughly half of what comparable insured individuals spend. This pattern is consistent with episodic, acute-care-dominated utilization rather than the sustained chronic-disease management that produces the largest expenditures under full coverage.

The Medicaid comparison is worth a separate note. Medicaid beneficiaries at 4+ conditions spend slightly *more* conditionally than Privately insured counterparts ($29,817 vs. $25,209). This is plausibly consistent with selection on unobserved severity within the coarse \"4+ conditions\" category — the Medicaid population is likely sicker on dimensions not captured by the condition count — and it illustrates why naive comparisons of per-capita spending across payer types are so often misleading in policy discussions.

Taken together: across both the high-cost tail models and the positive-expenditure GLM, multimorbidity emerges as the dominant driver of spending concentration. Relative to individuals with no chronic conditions, those with four or more conditions are substantially more likely to enter the top 5% of expenditure and incur nearly $20,000 higher annual spending conditional on positive use. Insurance coverage modestly modulates this gradient but does not overturn it: the uninsured consistently exhibit lower observed spending even at high morbidity levels, suggesting that differences reflect constrained access and lower intensity of care rather than lower clinical need.
", twopart_table_md, "

## Why these findings matter beyond the paper

The pattern has direct implications for several applied domains.

**Risk adjustment.** ACA-exchange and Medicare Advantage risk-adjustment models attempt to pay plans for the expected cost of their enrollees. The finding that clinical morbidity dominates other covariates validates the architecture of those models (they are built around condition categories), but the near-null effects of education and income suggest that adding social determinants as separate risk adjusters may add less than proponents argue, at least for expenditure prediction on a one-year horizon.

**Medicaid rate-setting.** The conditional-spending premium in Medicaid at high morbidity levels is consistent with the hypothesis that Medicaid enrolls a sicker slice of the population at each observed risk score. This has immediate implications for capitation rate-setting: if risk scores do not fully capture within-category severity, Medicaid managed care organizations face systematic underpayment on their sickest enrollees, with predictable effects on access and network composition.

**The cost of non-coverage.** The uninsured pattern — near-universal participation, suppressed conditional spending — is a quantitative characterization of what \"lack of access\" looks like at the population level. It is not that uninsured individuals avoid the system; it is that their engagement with it is shallower and more reactive. For any cost-benefit analysis of coverage expansion, this is the correct baseline to compare against: the counterfactual is not zero spending, it is $13,000 instead of $25,000 on the same clinical profile, potentially with different downstream health outcomes, although this project does not estimate those effects directly.

**High-cost patient targeting.** Every integrated delivery system and health plan invests in identifying the \"rising-risk\" and \"high-risk\" tails of their population for care management. The finding that even a main-effects model captures about 11% of the deviance in tail-membership sets a realistic ceiling on what pure claims-based prediction can achieve at this level of covariates. Improving beyond this requires either finer clinical data (labs, vitals, functional status) or temporal information (utilization trajectories) — and knowing the ceiling is itself useful to anyone deciding how much to invest in analytics infrastructure.

## What this project demonstrates about me as an analyst

The technical skills are legible from the code: survey-weighted GLMs, two-part models, average marginal effects with delta-method standard errors, reproducible pipelines in R, publication-ready visualization. Those are table stakes.

What is harder to demonstrate, and what this project is designed to show, is judgment: choosing a Gamma GLM over log-OLS to avoid retransformation bias, computing weighted rather than unweighted AMEs so the estimates describe the population rather than the sample, building a two-part decomposition so the participation and intensity margins are not conflated, and reporting that the interaction specification adds negligible pseudo-R² rather than hiding the result because it complicates the headline. Each of these decisions has a simpler alternative that would have produced cleaner-looking output but less defensible estimates.

## Technical summary

- **Data:** 2022 MEPS Full-Year Consolidated File (HC-243), analytical sample n = 17,909 adults 18+
- **Survey design:** stratified multi-stage cluster sample, handled via `survey::svydesign` with design weights, strata, and PSU
- **Models fit:**
  - Logistic (quasibinomial, survey-weighted): Pr(Top 5%), Pr(Top 1%), Pr(Y > 0), each under three specifications (demographics; + morbidity; + morbidity×insurance interaction)
  - Gamma GLM (log link, survey-weighted): E[Y | Y > 0] under the same three specifications
- **Inference:** average marginal effects via `marginaleffects::avg_slopes()` with weights explicitly passed through `model.frame()\\$(weights)`; delta-method standard errors
- **Deliverables:** six publication-quality figures, two-part expected-spending table for six representative profiles, full results narrative, machine-readable AME and prediction tables for reproducibility
- **Stack:** R 4.5, `survey`, `marginaleffects`, `gtsummary`, `flextable`, `ggplot2`, `gt`
")

writeLines(rmd_content, "docs/analytical_summary.Rmd")

tryCatch({
  rmarkdown::render("docs/analytical_summary.Rmd", output_dir = "docs", quiet = TRUE)
  cat("Report generated at 'docs/analytical_summary.html'.\n")
}, error = function(e) {
  cat("Error rendering report. Make sure pandoc is installed.\n")
  cat("Error message:", e$message, "\n")
})

cat("Step 8 complete.\n")
